[[redirects]]
  from = "/*"
  to = "https://scheduler-project-server.onrender.com"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"